version: "3"

services:
  gsp_api:
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    build:
      context: ""
      dockerfile: Dockerfile
    ports:
      - 8090:80
    volumes:
#      - MOUNT THE FLASK APP CODE
      - ./GSP_API:/app/GSP_API
#      - MOUNT THE DATA
      - /Users/rchales/data/geoglowsdata:/mnt/output